# andrew-customer ENV
apiVersion: v1
kind: ConfigMap
metadata:
  name: andrew-customer-configmap
data:
  NODE_ENV: "production"
---
# andrew-customer ENV SECRETS (BASE64)
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: andrew-customer-secrets
data: 
  GOOGLE_API_KEK: QUl6YVN5RGlfc3ZhaW9DNGZPRGFYRXNVZFF2SjNRVWdUYi1aOXRr
---
# andrew-customer DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andrew-customer-deployment
  labels:
    tier: andrew-customer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      tier: andrew-customer
  template:
    metadata:
      labels:
        tier: andrew-customer
    spec:
      containers:
        - name: andrew-customer
          image: antoineleguillou/andrew-customer:14-03-2024.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 350m
              memory: 450Mi
            requests:
              cpu: 250m
              memory: 250Mi
          envFrom:
            - configMapRef:
                name: andrew-customer-configmap
            - secretRef:
                name: andrew-customer-secrets
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
# andrew-customer SERVICES
apiVersion: v1
kind: Service
metadata:
  name: andrew-customer-service
spec:
  selector:
    tier: andrew-customer
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: public